### ISSUE TITLE
mp3play cannot run on your system

### ISSUE THREAD

**Issue by sudeep611** [michaelgundlach/mp3play#6]
> > > import mp3play
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/mp3play/**init**.py", line 6, in <module>
> > >     raise Exception("mp3play can't run on your operating system.")
> > > Exception: mp3play can't run on your operating system.

**Comment by sudeep611** [comment]
# This module runs only in windows.

```
if os.name == 'nt':
    from .windows import AudioClip as _PlatformSpecificAudioClip
else:
    raise Exception("mp3play can't run on your operating system.")
```
